# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kenan Can
tagline:          '</>'
description:      'Güvenliğe ilgi duyan biri'
url:              https://kenancn.github.io/

author:
  name:           '</>'
  url:            https://twitter.com/kenancn2

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
